version: '3.5'

services:
    nginx-proxy:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./php-app:/var/www/html
            - ./proxy/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - php-network
    php-app:
        image: php:fpm
        volumes:
            - ./php-app:/var/www/html
        networks:
            - php-network

networks:
  php-network:
    name: php-network
    driver: bridge
